//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCPDP_Data
    {
        public int Id { get; set; }
        public string SubmissionQtr { get; set; }
        public string DataLevel { get; set; }
        public string PlanIDQualifier { get; set; }
        public string PlanName { get; set; }
        public string ServiceProviderIDQualifier { get; set; }
        public string ServiceProviderID { get; set; }
        public string PharmacyServiceType { get; set; }
        public string ProductIDQualifier { get; set; }
        public string ProductID { get; set; }
        public string ProductDescription { get; set; }
        public string DAW { get; set; }
        public string TotalQuantity { get; set; }
        public string UnitofMeasure { get; set; }
        public string Filler1 { get; set; }
        public string RebateDaysSupply { get; set; }
        public string PrescriptionType { get; set; }
        public string TotalNumberofPresciptions { get; set; }
        public string PrescriptionNumberQualifier { get; set; }
        public string PrescriptionNumber { get; set; }
        public string DateofService { get; set; }
        public string TherapeuticClassCodeQualifier { get; set; }
        public string TherapeuticClassCode { get; set; }
        public string TherapeuticClassDescription { get; set; }
        public string ReimbursementQualifier { get; set; }
        public string ReimbursementAmount { get; set; }
        public string ReimbursementDate { get; set; }
        public string PatientLiability { get; set; }
        public string FillNumber { get; set; }
        public string RecordPurposeIndicator { get; set; }
        public string RebatePerUnitAmount { get; set; }
        public string RequestedRebateAmount { get; set; }
        public string PrescriberIDQualifier { get; set; }
        public string PrescriberID { get; set; }
        public string ClaimNumber { get; set; }
        public int ProductNDC { get; set; }
        public int PlanIdCode { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Plan Plan { get; set; }
    }
}
