//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string NDC { get; set; }
        public string Description { get; set; }
        public decimal WAC { get; set; }
        public string Size { get; set; }
        public int PharmaId { get; set; }
    
        public virtual Pharma Pharma { get; set; }
    }
}
